"""
Build MVP exam points from option-level textbook evidence.

This asset is intentionally separate from exam_points_v6.json.  The old exam
point file came from coarse question/QA inference; this one is anchored in
option-level evidence cards generated by the four-role pipeline.
"""

from __future__ import annotations

import hashlib
import json
import re
from collections import Counter, OrderedDict
from datetime import date
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[2]
WORKBENCH = ROOT / "cams工作台"
DATA = WORKBENCH / "data"

OPTION_EVIDENCE = DATA / "option_evidence_map.json"
QA_BINDINGS = DATA / "qa_bindings.json"
QA_RECORDS = DATA / "qa.json"
CARD_FILES = [
    DATA / "cards_v6_sentence.json",
    DATA / "cards_v6_except_ch2_sentence.json",
]
OUT = DATA / "exam_points_from_option_evidence_mvp.json"


def read_json(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8"))


def write_json(path: Path, data: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8")


def load_cards() -> dict[str, dict[str, Any]]:
    cards: dict[str, dict[str, Any]] = {}
    for path in CARD_FILES:
        if not path.exists():
            continue
        raw = read_json(path)
        rows = raw.get("cards", raw) if isinstance(raw, dict) else raw
        if not isinstance(rows, list):
            continue
        for card in rows:
            cid = card.get("card_id")
            if cid and cid not in cards:
                cards[cid] = card
    return cards


def compact(text: str, limit: int = 180) -> str:
    text = re.sub(r"\s+", " ", text or "").strip()
    if len(text) <= limit:
        return text
    return text[: max(0, limit - 1)] + "…"


def unique_extend(target: list[Any], values: list[Any]) -> None:
    for value in values:
        if value and value not in target:
            target.append(value)


def evidence_card_ids(option: dict[str, Any]) -> list[str]:
    return [
        card.get("card_id")
        for card in option.get("evidence_cards", [])
        if card.get("card_id")
    ]


def main_card_id(question_id: str, option: dict[str, Any]) -> str:
    cards = option.get("evidence_cards", [])
    direct = [card.get("card_id") for card in cards if card.get("support_type") == "direct" and card.get("card_id")]
    if direct:
        return direct[0]
    indirect = [card.get("card_id") for card in cards if card.get("card_id")]
    if indirect:
        return indirect[0]
    return f"{question_id}_{option.get('option', 'unknown')}_no_card"


def point_id(key: str) -> str:
    safe = re.sub(r"[^a-zA-Z0-9_]+", "_", key).strip("_").lower()
    if len(safe) <= 42:
        return "ep_opt_" + safe
    digest = hashlib.sha1(key.encode("utf-8")).hexdigest()[:10]
    return "ep_opt_" + safe[:30] + "_" + digest


def infer_type(title: str, body: str) -> str:
    text = f"{title} {body}"
    if re.search(r"红旗|危险信号|高风险|风险|可疑|异常|洗钱风险|恐怖融资风险", text):
        return "风险/红旗"
    if re.search(r"必须|要求|义务|禁止|规定|登记|尽职调查|EDD|CDD|法案|指令", text, re.I):
        return "法规义务/流程"
    if re.search(r"定义|是指|什么是|属于|阶段|拆分|通汇|私人银行|货币服务", text):
        return "概念/场景"
    return "待分类"


def status_for(item: dict[str, Any], option: dict[str, Any]) -> tuple[str, str, list[str]]:
    if item.get("validation_issues") or item.get("source_data_issues"):
        return "needs_manual", "low", ["source_data_fix"]
    if option.get("evidence_status") == "direct" and not option.get("needs_teacher_review"):
        return "ai_candidate", "high", []
    if option.get("evidence_status") in {"direct", "indirect"}:
        return "needs_evidence", "medium", ["teacher_review"]
    return "needs_evidence", "low", ["evidence"]


def title_for(option: dict[str, Any], cards_by_id: dict[str, dict[str, Any]]) -> str:
    text = option.get("option_text") or ""
    if 4 <= len(text) <= 34:
        return text
    for cid in evidence_card_ids(option):
        card = cards_by_id.get(cid) or {}
        for field in ["knowledge", "citation"]:
            value = compact(card.get(field) or "", 34)
            if value:
                return value
    return compact(text or "未命名考点", 34)


def qa_indexes() -> tuple[dict[str, list[str]], dict[str, dict[str, Any]]]:
    qa_by_question: dict[str, list[str]] = {}
    qa_by_id: dict[str, dict[str, Any]] = {}

    if QA_RECORDS.exists():
        qa = read_json(QA_RECORDS)
        for record in qa.get("records", []):
            if record.get("id"):
                qa_by_id[record["id"]] = record

    if QA_BINDINGS.exists():
        bindings = read_json(QA_BINDINGS)
        for binding in bindings.get("bindings", []):
            qid = binding.get("bound_question_id")
            qaid = binding.get("qa_id")
            if qid and qaid:
                qa_by_question.setdefault(qid, [])
                if qaid not in qa_by_question[qid]:
                    qa_by_question[qid].append(qaid)
    return qa_by_question, qa_by_id


def build() -> dict[str, Any]:
    option_evidence = read_json(OPTION_EVIDENCE)
    cards_by_id = load_cards()
    qa_by_question, qa_by_id = qa_indexes()
    today = date.today().isoformat()
    groups: OrderedDict[str, dict[str, Any]] = OrderedDict()

    for item in option_evidence.get("items", []):
        qid = item.get("question_id")
        if not qid:
            continue
        question_traps = [
            opt.get("common_trap", "")
            for opt in item.get("options", [])
            if opt.get("common_trap")
        ]

        for option in item.get("options", []):
            if not option.get("is_correct_answer"):
                continue

            key = main_card_id(qid, option)
            if key not in groups:
                title = title_for(option, cards_by_id)
                body = " ".join(
                    [
                        option.get("option_text", ""),
                        option.get("explanation", ""),
                        option.get("common_trap", ""),
                    ]
                )
                status, confidence, needs = status_for(item, option)
                groups[key] = {
                    "id": point_id(key),
                    "title": title,
                    "status": status,
                    "type": infer_type(title, body),
                    "source_card_ids": [],
                    "question_ids": [],
                    "qa_ids": [],
                    "student_confusion": "",
                    "reason": "",
                    "teacher_note": "",
                    "created_from": "option_evidence",
                    "confidence": confidence,
                    "needs": needs[:],
                    "updated_at": today,
                    "evidence_scope": item.get("evidence_scope", ""),
                    "source": "exam_points_from_option_evidence_mvp",
                    "option_bindings": [],
                    "source_card_details": [],
                    "student_confusions": [],
                    "source_data_issues": [],
                    "validation_issues": [],
                }

            ep = groups[key]
            source_ids = evidence_card_ids(option)
            unique_extend(ep["source_card_ids"], source_ids)
            unique_extend(ep["question_ids"], [qid])
            unique_extend(ep["qa_ids"], qa_by_question.get(qid, []))
            unique_extend(ep["source_data_issues"], item.get("source_data_issues", []))
            unique_extend(ep["validation_issues"], item.get("validation_issues", []))
            unique_extend(ep["student_confusions"], [option.get("common_trap", "")])
            unique_extend(ep["student_confusions"], question_traps[:3])

            status, confidence, needs = status_for(item, option)
            if ep["status"] == "ai_candidate" and status != "ai_candidate":
                ep["status"] = status
                ep["confidence"] = confidence
            unique_extend(ep["needs"], needs)

            ep["option_bindings"].append(
                {
                    "question_id": qid,
                    "option": option.get("option"),
                    "option_text": option.get("option_text", ""),
                    "judgement": option.get("judgement", ""),
                    "evidence_status": option.get("evidence_status", ""),
                    "evidence_card_ids": source_ids,
                    "explanation": option.get("explanation", ""),
                    "common_trap": option.get("common_trap", ""),
                    "needs_teacher_review": bool(option.get("needs_teacher_review")),
                    "teacher_review_reason": option.get("teacher_review_reason", ""),
                }
            )

            for card in option.get("evidence_cards", []):
                cid = card.get("card_id")
                if not cid:
                    continue
                if any(row.get("card_id") == cid for row in ep["source_card_details"]):
                    continue
                base = cards_by_id.get(cid, {})
                ep["source_card_details"].append(
                    {
                        "card_id": cid,
                        "support_type": card.get("support_type", ""),
                        "relevance": card.get("relevance", ""),
                        "quote": card.get("citation") or card.get("quote") or base.get("citation", ""),
                        "knowledge": card.get("knowledge") or base.get("knowledge", ""),
                        "reason": card.get("reason", ""),
                        "chapter_path": card.get("chapter_path") or base.get("chapter_path", ""),
                    }
                )

    exam_points = list(groups.values())
    for ep in exam_points:
        first_binding = ep["option_bindings"][0] if ep["option_bindings"] else {}
        evidence_note = "、".join(ep["source_card_ids"][:4]) or "暂无直接句卡"
        ep["student_confusion"] = compact("；".join(ep.pop("student_confusions", [])), 360)
        ep["reason"] = compact(
            f"由题目 {first_binding.get('question_id', '')} 的正确选项 {first_binding.get('option', '')} 反推："
            f"{first_binding.get('option_text', ep['title'])}。候选教材证据：{evidence_note}。"
            "该考点需教研确认后才能作为正式考点。",
            520,
        )
        if ep["source_data_issues"]:
            ep["status"] = "needs_manual"
            unique_extend(ep["needs"], ["source_data_fix"])
        if ep["validation_issues"] and ep["status"] == "ai_candidate":
            ep["status"] = "needs_manual"
            unique_extend(ep["needs"], ["validation"])
        ep["needs"] = sorted(ep["needs"])

    status_counts = Counter(ep["status"] for ep in exam_points)
    type_counts = Counter(ep["type"] for ep in exam_points)
    needs_counts = Counter(need for ep in exam_points for need in ep.get("needs", []))

    return {
        "version": "0.1",
        "asset_note": "MVP候选考点：由题目、选项、解析和选项级教材证据反推生成，供教研审核，不等同于最终定稿。",
        "source_scope": "option_evidence_map.json",
        "evidence_scope": "option-level-card-bindings",
        "generated_at": today,
        "exam_points": exam_points,
        "stats": {
            "total_exam_points": len(exam_points),
            "source_questions": len({qid for ep in exam_points for qid in ep.get("question_ids", [])}),
            "source_cards": len({cid for ep in exam_points for cid in ep.get("source_card_ids", [])}),
            "status_counts": dict(status_counts),
            "type_counts": dict(type_counts),
            "needs_counts": dict(needs_counts),
            "qa_records_attached": len({qaid for ep in exam_points for qaid in ep.get("qa_ids", [])}),
        },
    }


def main() -> None:
    payload = build()
    write_json(OUT, payload)
    print(f"wrote {OUT}")
    print(json.dumps(payload["stats"], ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
