"""
Build candidate exam points and option-to-textbook-evidence mappings.

Input: output/step1_ai_responses/q_*.json generated by the four-role pipeline.
Output:
- output/exam_point_mapping/option_evidence_mapping.json
- output/exam_point_mapping/option_evidence_mapping.csv
- output/exam_point_mapping/candidate_exam_points.json
- output/exam_point_mapping/audit_report.md

Important: generated exam points are candidates for teaching review, not
confirmed exam-point data.
"""

from __future__ import annotations

import argparse
import csv
import json
from collections import Counter, defaultdict
from datetime import datetime
from pathlib import Path
from typing import Any


BASE = Path(__file__).resolve().parent
ROOT = BASE.parent
DATA = ROOT / "cams工作台" / "data"
STEP1_DIR = BASE / "output" / "step1_ai_responses"
OUTPUT_DIR = BASE / "output" / "exam_point_mapping"

EVIDENCE_FILES = {
    "ch2": DATA / "cards_ch2.json",
    "v6-sentence": DATA / "cards_v6_sentence.json",
    "v6-except-ch2": DATA / "cards_v6_except_ch2_sentence.json",
}


def read_json(path: Path) -> Any:
    with path.open("r", encoding="utf-8") as f:
        return json.load(f)


def write_json(path: Path, data: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)


def load_cards() -> dict[str, dict[str, Any]]:
    cards_by_id: dict[str, dict[str, Any]] = {}
    for scope, path in EVIDENCE_FILES.items():
        if not path.exists():
            continue
        raw = read_json(path)
        cards = raw.get("cards", raw) if isinstance(raw, dict) else raw
        if not isinstance(cards, list):
            continue
        for card in cards:
            cid = card.get("card_id")
            if cid:
                cards_by_id[cid] = {**card, "_source_scope": scope}
    return cards_by_id


def load_step1_outputs(step1_dir: Path) -> list[dict[str, Any]]:
    outputs = []
    for path in sorted(step1_dir.glob("q_*.json")):
        try:
            data = read_json(path)
        except Exception as exc:
            outputs.append({"_path": str(path), "_load_error": str(exc)})
            continue
        data["_path"] = str(path)
        outputs.append(data)
    return outputs


def normalize_options(options: Any) -> dict[str, str]:
    if isinstance(options, dict):
        return {str(k): str(v) for k, v in options.items()}
    if isinstance(options, list):
        return {chr(65 + i): str(v) for i, v in enumerate(options)}
    return {}


def plan_by_option(search_plan: Any) -> dict[str, dict[str, Any]]:
    if not isinstance(search_plan, dict):
        return {}
    out: dict[str, dict[str, Any]] = {}
    for item in search_plan.get("options", []):
        if isinstance(item, dict) and item.get("option"):
            out[str(item["option"])] = item
    return out


def card_snapshot(card_id: str, cards_by_id: dict[str, dict[str, Any]], fallback_quote: str = "") -> dict[str, Any]:
    card = cards_by_id.get(card_id, {})
    return {
        "card_id": card_id,
        "evidence_scope": card.get("evidence_scope") or card.get("_source_scope", ""),
        "chapter_path": card.get("chapter_path", ""),
        "knowledge": card.get("knowledge", ""),
        "citation": card.get("citation") or fallback_quote,
        "source_asset": card.get("source_asset", ""),
        "source_line_start": card.get("source_line_start"),
        "source_line_end": card.get("source_line_end"),
    }


def build_rows(outputs: list[dict[str, Any]], cards_by_id: dict[str, dict[str, Any]]) -> tuple[list[dict[str, Any]], dict[str, dict[str, Any]], list[str]]:
    rows: list[dict[str, Any]] = []
    exam_points: dict[str, dict[str, Any]] = {}
    issues: list[str] = []

    for data in outputs:
        if data.get("_load_error"):
            issues.append(f"load_error: {data.get('_path')} {data.get('_load_error')}")
            continue
        qid = data.get("question_id", "")
        options = normalize_options(data.get("options"))
        search_plan = data.get("search_plan", {})
        question_focus = search_plan.get("question_focus") if isinstance(search_plan, dict) else ""
        question_focus = question_focus or data.get("stem", "")
        plan_options = plan_by_option(search_plan)
        answer = data.get("answer", "")
        quality = data.get("quality", {})
        evidence_scope = data.get("evidence_scope", "")

        option_analysis = data.get("option_analysis", [])
        if not isinstance(option_analysis, list):
            issues.append(f"{qid}: missing option_analysis list")
            continue

        for item in option_analysis:
            if not isinstance(item, dict):
                continue
            option = str(item.get("option", ""))
            plan_item = plan_options.get(option, {})
            evidence_cards = item.get("evidence_cards", [])
            if not isinstance(evidence_cards, list):
                evidence_cards = []

            snapshots = []
            for ev in evidence_cards:
                if not isinstance(ev, dict):
                    continue
                cid = ev.get("card_id")
                if not cid:
                    continue
                snap = card_snapshot(str(cid), cards_by_id, fallback_quote=ev.get("quote", ""))
                snapshots.append(
                    {
                        **snap,
                        "support_type": ev.get("support_type", ""),
                        "relevance": ev.get("relevance", ""),
                        "reason": ev.get("reason", ""),
                    }
                )

            row = {
                "question_id": qid,
                "stem": data.get("stem", ""),
                "answer": answer,
                "question_focus": question_focus,
                "question_status": data.get("status", ""),
                "retrieval_mode": data.get("retrieval_mode", ""),
                "evidence_scope": evidence_scope,
                "quality_validation_issues": quality.get("validation_issues", []),
                "option": option,
                "option_text": item.get("option_text") or options.get(option, ""),
                "option_claim": plan_item.get("option_claim", ""),
                "judgement": item.get("judgement", ""),
                "is_correct_answer": bool(item.get("is_correct_answer")),
                "evidence_status": item.get("evidence_status", ""),
                "evidence_card_ids": [snap["card_id"] for snap in snapshots],
                "evidence_cards": snapshots,
                "explanation": item.get("explanation", ""),
                "common_trap": item.get("common_trap", ""),
                "needs_teacher_review": bool(item.get("needs_teacher_review")),
                "teacher_review_reason": item.get("teacher_review_reason", ""),
                "candidate_exam_point_ids": [],
            }
            rows.append(row)

            if not row["is_correct_answer"]:
                continue
            directish = [snap for snap in snapshots if snap.get("support_type") in {"direct", "indirect"}]
            if not directish:
                continue
            for snap in directish:
                point_key = (question_focus, row["option_claim"] or row["option_text"])
                point_id = exam_points.get(str(point_key), {}).get("candidate_exam_point_id")
                if not point_id:
                    point_id = f"cep_{len(exam_points) + 1:05d}"
                    point_name = row["option_claim"] or row["option_text"] or question_focus
                    exam_points[str(point_key)] = {
                        "candidate_exam_point_id": point_id,
                        "status": "candidate",
                        "source": "four_role_option_evidence",
                        "confidence": "medium" if snap.get("support_type") == "indirect" else "high",
                        "exam_point_name": point_name,
                        "parent_focus": question_focus,
                        "core_textbook_evidence": [snap],
                        "related_questions": [],
                        "common_traps": [],
                        "teacher_review": {
                            "required": False,
                            "reason": "",
                            "decision": "pending",
                        },
                    }
                else:
                    point = exam_points[str(point_key)]
                    if snap.get("support_type") == "direct":
                        point["confidence"] = "high"
                    if snap["card_id"] not in {ev.get("card_id") for ev in point["core_textbook_evidence"]}:
                        point["core_textbook_evidence"].append(snap)
                point = exam_points[str(point_key)]
                point["related_questions"].append(
                    {
                        "question_id": qid,
                        "option": option,
                        "option_text": row["option_text"],
                        "judgement": row["judgement"],
                        "evidence_status": row["evidence_status"],
                    }
                )
                if row["common_trap"]:
                    point["common_traps"].append(row["common_trap"])
                if point_id not in row["candidate_exam_point_ids"]:
                    row["candidate_exam_point_ids"].append(point_id)

    # Deduplicate related questions and traps in-place.
    for point in exam_points.values():
        seen_q = set()
        unique_q = []
        for rel in point["related_questions"]:
            key = (rel["question_id"], rel["option"])
            if key not in seen_q:
                seen_q.add(key)
                unique_q.append(rel)
        point["related_questions"] = unique_q
        point["common_traps"] = list(dict.fromkeys(point["common_traps"]))
    return rows, exam_points, issues


def write_csv(path: Path, rows: list[dict[str, Any]]) -> None:
    fieldnames = [
        "question_id",
        "option",
        "judgement",
        "is_correct_answer",
        "evidence_status",
        "candidate_exam_point_ids",
        "evidence_card_ids",
        "evidence_scope",
        "question_focus",
        "option_text",
        "option_claim",
        "explanation",
        "common_trap",
        "needs_teacher_review",
        "teacher_review_reason",
    ]
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8-sig", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        for row in rows:
            flat = {key: row.get(key, "") for key in fieldnames}
            flat["candidate_exam_point_ids"] = ",".join(row.get("candidate_exam_point_ids", []))
            flat["evidence_card_ids"] = ",".join(row.get("evidence_card_ids", []))
            writer.writerow(flat)


def build_audit(rows: list[dict[str, Any]], exam_points: list[dict[str, Any]], issues: list[str]) -> str:
    by_scope = Counter(row.get("evidence_scope", "") for row in rows)
    by_status = Counter(row.get("evidence_status", "") for row in rows)
    by_question = defaultdict(list)
    for row in rows:
        by_question[row["question_id"]].append(row)

    report = [
        "# Candidate Exam Point Mapping Audit",
        "",
        f"- generated_at: {datetime.now().astimezone().isoformat(timespec='seconds')}",
        f"- questions: {len(by_question)}",
        f"- option_rows: {len(rows)}",
        f"- candidate_exam_points: {len(exam_points)}",
        f"- issues: {len(issues)}",
        f"- evidence_scope_counts: {dict(by_scope)}",
        f"- evidence_status_counts: {dict(by_status)}",
        "",
        "## Issues",
    ]
    report.extend(f"- {issue}" for issue in issues[:100])
    if not issues:
        report.append("- none")

    report.append("")
    report.append("## Question Coverage")
    for qid, qrows in sorted(by_question.items()):
        direct = sum(1 for row in qrows if row["evidence_status"] == "direct")
        indirect = sum(1 for row in qrows if row["evidence_status"] == "indirect")
        none = sum(1 for row in qrows if row["evidence_status"] == "none")
        points = sorted({pid for row in qrows for pid in row.get("candidate_exam_point_ids", [])})
        report.append(f"- {qid}: options={len(qrows)} direct={direct} indirect={indirect} none={none} candidate_points={','.join(points) or '-'}")

    report.append("")
    report.append("## Candidate Exam Points")
    for point in exam_points[:50]:
        report.append(f"- {point['candidate_exam_point_id']} | {point['exam_point_name']}")
        for ev in point.get("core_textbook_evidence", [])[:2]:
            report.append(f"  - {ev.get('card_id')} | {ev.get('chapter_path')}")
            report.append(f"  - citation: {ev.get('citation')}")
    return "\n".join(report) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Build candidate exam-point and option evidence mapping tables.")
    parser.add_argument("--step1-dir", type=Path, default=STEP1_DIR)
    parser.add_argument("--output-dir", type=Path, default=OUTPUT_DIR)
    args = parser.parse_args(argv)

    cards_by_id = load_cards()
    outputs = load_step1_outputs(args.step1_dir)
    rows, exam_points_by_key, issues = build_rows(outputs, cards_by_id)
    exam_points = list(exam_points_by_key.values())

    payload = {
        "schema_version": "option_exam_point_mapping_v1",
        "asset_note": (
            "Option-level textbook evidence mapping generated from four-role pipeline outputs. "
            "Candidate exam points are inferred from correct options with direct/indirect textbook evidence; "
            "they require teaching review before becoming confirmed exam points."
        ),
        "generated_at": datetime.now().astimezone().isoformat(timespec="seconds"),
        "source_step1_dir": str(args.step1_dir),
        "option_rows": rows,
    }
    point_payload = {
        "schema_version": "candidate_exam_points_v1",
        "asset_note": (
            "Candidate exam points inferred from four-role option evidence. These are not confirmed exam points."
        ),
        "generated_at": payload["generated_at"],
        "candidate_exam_points": exam_points,
    }

    args.output_dir.mkdir(parents=True, exist_ok=True)
    write_json(args.output_dir / "option_evidence_mapping.json", payload)
    write_json(args.output_dir / "candidate_exam_points.json", point_payload)
    write_csv(args.output_dir / "option_evidence_mapping.csv", rows)
    audit = build_audit(rows, exam_points, issues)
    (args.output_dir / "audit_report.md").write_text(audit, encoding="utf-8")

    print(
        json.dumps(
            {
                "questions": len({row["question_id"] for row in rows}),
                "option_rows": len(rows),
                "candidate_exam_points": len(exam_points),
                "issues": len(issues),
                "output_dir": str(args.output_dir),
            },
            ensure_ascii=False,
            indent=2,
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
