"""
v4.4 Step 7B: apply approved review decisions.

This step turns Step 7A advisory decisions into final import packages. It does
not call an LLM and does not change Step 6 artifacts. Every non-imported item is
kept in an archive and every accepted / rewritten / rejected action is recorded
in decision_trace.jsonl.

v4.4 additionally creates deterministic KnowledgeGroup records after accepted
items are known. SectionGroup and RuleGroup are generated by code rather than
free LLM grouping.
"""

from __future__ import annotations

import argparse
import hashlib
import json
from collections import Counter
from datetime import datetime
from pathlib import Path
from typing import Any


SCRIPT_DIR = Path(__file__).resolve().parent
DEFAULT_MIDDLE_DIR = SCRIPT_DIR / "中间产物"
DEFAULT_LAYER_DIR = DEFAULT_MIDDLE_DIR / "step6_layers"
DEFAULT_DECISIONS = DEFAULT_MIDDLE_DIR / "step7_preapproval" / "preapproval_decisions.jsonl"
DEFAULT_OUT_DIR = DEFAULT_MIDDLE_DIR / "step7_final_package"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Apply v4.4 Step 7 approved review decisions.")
    parser.add_argument("--layer-dir", type=Path, default=DEFAULT_LAYER_DIR)
    parser.add_argument("--decisions", type=Path, default=DEFAULT_DECISIONS)
    parser.add_argument("--out-dir", type=Path, default=DEFAULT_OUT_DIR)
    parser.add_argument(
        "--approval-label",
        default="user_approved_step7a",
        help="Human-readable label written into decision traces.",
    )
    return parser.parse_args()


def read_jsonl(path: Path, required: bool = True) -> list[dict[str, Any]]:
    if not path.exists():
        if required:
            raise FileNotFoundError(f"JSONL not found: {path}")
        return []
    return [json.loads(line) for line in path.read_text(encoding="utf-8-sig").splitlines() if line.strip()]


def write_jsonl(path: Path, rows: list[dict[str, Any]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("".join(json.dumps(row, ensure_ascii=False) + "\n" for row in rows), encoding="utf-8")


def stable_id(prefix: str, parts: list[str]) -> str:
    digest = hashlib.sha1("|".join(parts).encode("utf-8")).hexdigest()[:14]
    return f"{prefix}:{digest}"


def now_iso() -> str:
    return datetime.now().isoformat(timespec="seconds")


def source_code(row: dict[str, Any]) -> str:
    section_node_id = str(row.get("section_node_id") or "").strip()
    textbook_id = str(row.get("textbook_id") or "").strip()
    base = section_node_id or textbook_id or "unknown-source"
    line_start = row.get("line_start")
    line_end = row.get("line_end")
    if line_start not in (None, "", 0) or line_end not in (None, "", 0):
        return f"{base}:L{line_start or ''}-L{line_end or ''}"
    return base


def ensure_source_code(item: dict[str, Any]) -> dict[str, Any]:
    item.setdefault("source_code", source_code(item))
    return item


def node_identity(node: dict[str, Any]) -> str:
    node_id = str(node.get("node_id") or "")
    if node_id:
        return node_id
    return stable_id("node-key", [str(node.get("name") or ""), str(node.get("type") or "")])


def edge_identity(edge: dict[str, Any]) -> str:
    return stable_id(
        "edge-key",
        [
            str(edge.get("source_node_id") or edge.get("source_name") or ""),
            str(edge.get("target_node_id") or edge.get("target_name") or ""),
            str(edge.get("type") or ""),
            str(edge.get("kg_layer") or ""),
        ],
    )


def rule_case_identity(rule_case: dict[str, Any]) -> str:
    rule_case_id = str(rule_case.get("rule_case_id") or "")
    if rule_case_id:
        return rule_case_id
    return stable_id(
        "rule-case-key",
        [
            str(rule_case.get("owner_node_id") or rule_case.get("owner_name") or ""),
            str(rule_case.get("case_name") or ""),
            str(rule_case.get("evidence_span") or ""),
        ],
    )


def final_node(row: dict[str, Any], final_layer: str, status: str, decision: dict[str, Any] | None = None) -> dict[str, Any]:
    item = dict(row)
    item["kg_layer"] = final_layer
    item["rule_cases"] = []
    item["rule_cases_step7_policy"] = "rule_cases_are_reviewed_separately"
    item["step7_status"] = status
    item["step7_layer"] = final_layer
    item["final_import_ready"] = True
    item["step7_generated_at"] = now_iso()
    if decision:
        item["step7_decision_id"] = decision.get("decision_id", "")
        item["step7_basis"] = decision.get("basis", "")
        item["step7_approval_label"] = decision.get("approval_label", "")
    return ensure_source_code(item)


def final_edge(row: dict[str, Any], final_layer: str, status: str, decision: dict[str, Any] | None = None) -> dict[str, Any]:
    item = dict(row)
    item["kg_layer"] = final_layer
    item["step7_status"] = status
    item["step7_layer"] = final_layer
    item["final_import_ready"] = True
    item["step7_generated_at"] = now_iso()
    if decision:
        item["step7_decision_id"] = decision.get("decision_id", "")
        item["step7_basis"] = decision.get("basis", "")
        item["step7_approval_label"] = decision.get("approval_label", "")
    return ensure_source_code(item)


def final_rule_case(row: dict[str, Any], status: str, decision: dict[str, Any] | None = None) -> dict[str, Any]:
    item = dict(row)
    item["kg_layer"] = "rule_case"
    item["step7_status"] = status
    item["step7_layer"] = "rule_case"
    item["final_import_ready"] = True
    item["step7_generated_at"] = now_iso()
    if not item.get("rule_case_id"):
        item["rule_case_id"] = rule_case_identity(item)
    if decision:
        item["step7_decision_id"] = decision.get("decision_id", "")
        item["step7_basis"] = decision.get("basis", "")
        item["step7_approval_label"] = decision.get("approval_label", "")
    return ensure_source_code(item)


def archived_item(
    source: dict[str, Any],
    archive_status: str,
    decision: dict[str, Any] | None,
    item_kind: str | None = None,
    extra: dict[str, Any] | None = None,
) -> dict[str, Any]:
    item = dict(source)
    item["archive_status"] = archive_status
    item["final_import_ready"] = False
    item["step7_generated_at"] = now_iso()
    if item_kind:
        item["item_kind"] = item_kind
    if decision:
        item["step7_decision_id"] = decision.get("decision_id", "")
        item["step7_recommendation"] = decision.get("recommendation", "")
        item["step7_action_detail"] = decision.get("action_detail", "")
        item["step7_basis"] = decision.get("basis", "")
        item["step7_approval_label"] = decision.get("approval_label", "")
    if extra:
        item.update(extra)
    return item


def trace_row(
    decision: dict[str, Any],
    result: str,
    imported_item_id: str = "",
    archived_item_id: str = "",
    note: str = "",
) -> dict[str, Any]:
    return {
        "decision_id": decision.get("decision_id", ""),
        "item_kind": decision.get("item_kind", ""),
        "item_id": decision.get("item_id", ""),
        "item_name": decision.get("item_name", ""),
        "item_type": decision.get("item_type", ""),
        "source_name": decision.get("source_name", ""),
        "target_name": decision.get("target_name", ""),
        "kg_layer": decision.get("kg_layer", ""),
        "recommendation": decision.get("recommendation", ""),
        "action_detail": decision.get("action_detail", ""),
        "target_layer": decision.get("target_layer", ""),
        "basis": decision.get("basis", ""),
        "approval_label": decision.get("approval_label", ""),
        "result": result,
        "imported_item_id": imported_item_id,
        "archived_item_id": archived_item_id,
        "note": note,
        "generated_at": now_iso(),
    }


def add_unique(rows: list[dict[str, Any]], row: dict[str, Any], key_func) -> bool:
    existing = {key_func(item) for item in rows}
    key = key_func(row)
    if key in existing:
        return False
    rows.append(row)
    return True


def group_identity(group: dict[str, Any]) -> str:
    return str(group.get("group_id") or "")


def group_member_identity(edge: dict[str, Any]) -> str:
    return str(edge.get("edge_id") or "")


def build_section_groups(nodes: list[dict[str, Any]]) -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
    grouped: dict[str, list[dict[str, Any]]] = {}
    for node in nodes:
        section_node_id = str(node.get("section_node_id") or "").strip()
        if not section_node_id:
            continue
        grouped.setdefault(section_node_id, []).append(node)

    groups: list[dict[str, Any]] = []
    edges: list[dict[str, Any]] = []
    for section_node_id, members in sorted(grouped.items()):
        first = members[0]
        section = str(first.get("section") or first.get("subsection") or section_node_id)
        group_id = stable_id(f"{first.get('textbook_id', '')}:group", [section_node_id, "SectionGroup"])
        group = ensure_source_code(
            {
                "group_id": group_id,
                "name": section,
                "type": "KnowledgeGroup",
                "group_type": "SectionGroup",
                "kg_layer": "knowledge_group",
                "textbook_id": first.get("textbook_id", ""),
                "textbook_name": first.get("textbook_name", ""),
                "chapter": first.get("chapter", ""),
                "section": first.get("section", ""),
                "subsection": first.get("subsection", ""),
                "section_node_id": section_node_id,
                "source_scope": first.get("source_scope", ""),
                "member_count": len(members),
                "anchor_node_id": "",
                "anchor_name": "",
                "creation_policy": "auto_by_section_node_id",
                "final_import_ready": True,
                "step7_generated_at": now_iso(),
            }
        )
        groups.append(group)
        for member in members:
            member_id = str(member.get("node_id") or "")
            if not member_id:
                continue
            edges.append(
                ensure_source_code(
                    {
                        "edge_id": stable_id(f"{first.get('textbook_id', '')}:groupedge", [group_id, member_id, "HAS_MEMBER"]),
                        "type": "HAS_MEMBER",
                        "kg_layer": "knowledge_group",
                        "source_group_id": group_id,
                        "source_node_id": group_id,
                        "source_name": group["name"],
                        "source_type": "KnowledgeGroup",
                        "target_node_id": member_id,
                        "target_name": member.get("name", ""),
                        "target_type": member.get("type", ""),
                        "textbook_id": member.get("textbook_id", ""),
                        "textbook_name": member.get("textbook_name", ""),
                        "chapter": member.get("chapter", ""),
                        "section": member.get("section", ""),
                        "subsection": member.get("subsection", ""),
                        "section_node_id": member.get("section_node_id", ""),
                        "source_scope": member.get("source_scope", ""),
                        "description": "知识点属于该小节知识组。",
                        "evidence_span": member.get("evidence_span", ""),
                        "confidence": 1.0,
                        "final_import_ready": True,
                        "step7_generated_at": now_iso(),
                    }
                )
            )
    return groups, edges


def build_rule_groups(rule_cases: list[dict[str, Any]]) -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
    grouped: dict[str, list[dict[str, Any]]] = {}
    for rule_case in rule_cases:
        owner_id = str(rule_case.get("owner_node_id") or rule_case.get("owner_name") or "").strip()
        if not owner_id:
            continue
        grouped.setdefault(owner_id, []).append(rule_case)

    groups: list[dict[str, Any]] = []
    edges: list[dict[str, Any]] = []
    for owner_id, cases in sorted(grouped.items()):
        first = cases[0]
        owner_name = str(first.get("owner_name") or owner_id)
        group_id = stable_id(f"{first.get('textbook_id', '')}:group", [owner_id, "RuleGroup"])
        group = ensure_source_code(
            {
                "group_id": group_id,
                "name": f"{owner_name}规则组",
                "type": "KnowledgeGroup",
                "group_type": "RuleGroup",
                "kg_layer": "knowledge_group",
                "textbook_id": first.get("textbook_id", ""),
                "textbook_name": first.get("textbook_name", ""),
                "chapter": first.get("chapter", ""),
                "section": first.get("section", ""),
                "subsection": first.get("subsection", ""),
                "section_node_id": first.get("section_node_id", ""),
                "source_scope": first.get("source_scope", ""),
                "member_count": len(cases),
                "anchor_node_id": first.get("owner_node_id", ""),
                "anchor_name": owner_name,
                "creation_policy": "auto_by_rule_case_owner",
                "final_import_ready": True,
                "step7_generated_at": now_iso(),
            }
        )
        groups.append(group)
        if first.get("owner_node_id"):
            edges.append(
                ensure_source_code(
                    {
                        "edge_id": stable_id(f"{first.get('textbook_id', '')}:groupedge", [group_id, str(first.get("owner_node_id") or ""), "HAS_ANCHOR"]),
                        "type": "HAS_ANCHOR",
                        "kg_layer": "knowledge_group",
                        "source_group_id": group_id,
                        "source_node_id": group_id,
                        "source_name": group["name"],
                        "source_type": "KnowledgeGroup",
                        "target_node_id": first.get("owner_node_id", ""),
                        "target_name": owner_name,
                        "target_type": first.get("owner_type", ""),
                        "textbook_id": first.get("textbook_id", ""),
                        "textbook_name": first.get("textbook_name", ""),
                        "chapter": first.get("chapter", ""),
                        "section": first.get("section", ""),
                        "subsection": first.get("subsection", ""),
                        "section_node_id": first.get("section_node_id", ""),
                        "source_scope": first.get("source_scope", ""),
                        "description": "规则组的锚点知识节点。",
                        "evidence_span": first.get("evidence_span", ""),
                        "confidence": 1.0,
                        "final_import_ready": True,
                        "step7_generated_at": now_iso(),
                    }
                )
            )
        for case in cases:
            case_id = str(case.get("rule_case_id") or "")
            if not case_id:
                continue
            edges.append(
                ensure_source_code(
                    {
                        "edge_id": stable_id(f"{first.get('textbook_id', '')}:groupedge", [group_id, case_id, "HAS_MEMBER"]),
                        "type": "HAS_MEMBER",
                        "kg_layer": "knowledge_group",
                        "source_group_id": group_id,
                        "source_node_id": group_id,
                        "source_name": group["name"],
                        "source_type": "KnowledgeGroup",
                        "target_node_id": case_id,
                        "target_name": case.get("case_name", ""),
                        "target_type": "RuleCase",
                        "textbook_id": case.get("textbook_id", ""),
                        "textbook_name": case.get("textbook_name", ""),
                        "chapter": case.get("chapter", ""),
                        "section": case.get("section", ""),
                        "subsection": case.get("subsection", ""),
                        "section_node_id": case.get("section_node_id", ""),
                        "source_scope": case.get("source_scope", ""),
                        "description": "规则案例属于该规则组。",
                        "evidence_span": case.get("evidence_span", ""),
                        "confidence": 1.0,
                        "final_import_ready": True,
                        "step7_generated_at": now_iso(),
                    }
                )
            )
    return groups, edges


def enrich_rewritten_edge(edge: dict[str, Any], nodes_by_name: dict[str, dict[str, Any]]) -> dict[str, Any]:
    item = dict(edge)
    source_name = str(item.get("source_name") or "")
    target_name = str(item.get("target_name") or "")
    source = nodes_by_name.get(source_name, {})
    target = nodes_by_name.get(target_name, {})
    item.setdefault("source_node_id", source.get("node_id", ""))
    item.setdefault("target_node_id", target.get("node_id", ""))
    item.setdefault("source_type", source.get("type", ""))
    item.setdefault("target_type", target.get("type", ""))
    if not item.get("edge_id"):
        item["edge_id"] = stable_id(
            "gaodai_shang:review-edge",
            [
                str(item.get("source_node_id") or source_name),
                str(item.get("target_node_id") or target_name),
                str(item.get("type") or ""),
            ],
        )
    return item


def merge_node_alias(final_nodes: list[dict[str, Any]], target_name: str, source: dict[str, Any], decision: dict[str, Any]) -> bool:
    if not target_name:
        return False
    source_name = str(source.get("name") or "")
    for node in final_nodes:
        if node.get("name") != target_name and node.get("node_id") != decision.get("rewritten_item", {}).get("target_node_id"):
            continue
        aliases = list(node.get("aliases") or [])
        if source_name and source_name != node.get("name") and source_name not in aliases:
            aliases.append(source_name)
        node["aliases"] = aliases
        merged = list(node.get("step7_merged_from_review_items") or [])
        merged.append(
            {
                "source_node_id": source.get("node_id", ""),
                "source_name": source_name,
                "source_type": source.get("type", ""),
                "evidence_span": source.get("evidence_span", ""),
                "decision_id": decision.get("decision_id", ""),
                "basis": decision.get("basis", ""),
            }
        )
        node["step7_merged_from_review_items"] = merged
        return True
    return False


def owner_exists(rule_case: dict[str, Any], final_nodes: list[dict[str, Any]]) -> bool:
    owner_id = str(rule_case.get("owner_node_id") or "")
    owner_name = str(rule_case.get("owner_name") or "")
    for node in final_nodes:
        if owner_id and node.get("node_id") == owner_id:
            return True
        if owner_name and node.get("name") == owner_name:
            return True
    return False


def edge_endpoints_exist(edge: dict[str, Any], final_nodes: list[dict[str, Any]]) -> tuple[bool, list[str]]:
    source_id = str(edge.get("source_node_id") or "")
    target_id = str(edge.get("target_node_id") or "")
    source_name = str(edge.get("source_name") or "")
    target_name = str(edge.get("target_name") or "")
    node_ids = {str(node.get("node_id") or "") for node in final_nodes if node.get("node_id")}
    node_names = {str(node.get("name") or "") for node in final_nodes if node.get("name")}
    missing: list[str] = []
    if source_id:
        if source_id not in node_ids:
            missing.append(f"source:{source_name or source_id}")
    elif source_name not in node_names:
        missing.append(f"source:{source_name or '<missing>'}")
    if target_id:
        if target_id not in node_ids:
            missing.append(f"target:{target_name or target_id}")
    elif target_name not in node_names:
        missing.append(f"target:{target_name or '<missing>'}")
    return (not missing, missing)


def is_core_target_layer(target_layer: str) -> bool:
    return target_layer in {"core", "explicit_core"}


def write_report(
    path: Path,
    final_core_nodes: list[dict[str, Any]],
    final_core_edges: list[dict[str, Any]],
    final_app_nodes: list[dict[str, Any]],
    final_app_edges: list[dict[str, Any]],
    final_rule_cases: list[dict[str, Any]],
    final_groups: list[dict[str, Any]],
    final_group_edges: list[dict[str, Any]],
    archived: list[dict[str, Any]],
    deferred: list[dict[str, Any]],
    traces: list[dict[str, Any]],
) -> None:
    decision_counts = Counter(str(row.get("result") or "") for row in traces)
    node_type_counts = Counter(str(row.get("type") or "") for row in final_core_nodes + final_app_nodes)
    edge_type_counts = Counter(str(row.get("type") or "") for row in final_core_edges + final_app_edges)
    rule_case_owner_counts = Counter(str(row.get("owner_type") or "") for row in final_rule_cases)

    group_type_counts = Counter(str(row.get("group_type") or "") for row in final_groups)
    group_edge_type_counts = Counter(str(row.get("type") or "") for row in final_group_edges)

    lines = [
        "# v4.4 Step 7B Review Landing Report",
        "",
        "## Final Import Package",
        f"- final_core_nodes: {len(final_core_nodes)}",
        f"- final_core_edges: {len(final_core_edges)}",
        f"- final_application_nodes: {len(final_app_nodes)}",
        f"- final_application_edges: {len(final_app_edges)}",
        f"- final_rule_cases: {len(final_rule_cases)}",
        f"- final_knowledge_groups: {len(final_groups)}",
        f"- final_knowledge_group_edges: {len(final_group_edges)}",
        f"- final_archived_items: {len(archived)}",
        f"- final_deferred_items: {len(deferred)}",
        f"- decision_trace_rows: {len(traces)}",
        "",
        "## Decision Results",
    ]
    for key, value in sorted(decision_counts.items()):
        lines.append(f"- {key}: {value}")

    lines.extend(["", "## Node Types"])
    for key, value in sorted(node_type_counts.items()):
        lines.append(f"- {key}: {value}")

    lines.extend(["", "## Edge Types"])
    for key, value in sorted(edge_type_counts.items()):
        lines.append(f"- {key}: {value}")

    lines.extend(["", "## Rule Case Owners"])
    if rule_case_owner_counts:
        for key, value in sorted(rule_case_owner_counts.items()):
            lines.append(f"- {key}: {value}")
    else:
        lines.append("- none")

    lines.extend(["", "## Knowledge Groups"])
    if group_type_counts:
        for key, value in sorted(group_type_counts.items()):
            lines.append(f"- {key}: {value}")
    else:
        lines.append("- none")

    lines.extend(["", "## Knowledge Group Edge Types"])
    if group_edge_type_counts:
        for key, value in sorted(group_edge_type_counts.items()):
            lines.append(f"- {key}: {value}")
    else:
        lines.append("- none")

    lines.extend(
        [
            "",
            "## Trace Policy",
            "- accept: item is written to a final import package.",
            "- rewrite: rewritten item is written to a final package; the original item is archived with the rewrite target.",
            "- reject: original item is archived and is not written to an import package.",
            "- defer: original item remains in final_review_pending.jsonl.",
            "- rule_case: only final_rule_cases.jsonl is expanded into rule-layer nodes/edges in Step 8.",
        ]
    )
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    args = parse_args()
    out_dir: Path = args.out_dir
    out_dir.mkdir(parents=True, exist_ok=True)

    explicit_core_nodes = read_jsonl(args.layer_dir / "explicit_core_nodes.jsonl")
    explicit_core_edges = read_jsonl(args.layer_dir / "explicit_core_edges.jsonl")
    existing_app_nodes = read_jsonl(args.layer_dir / "example_application_nodes.jsonl", required=False)
    existing_app_edges = read_jsonl(args.layer_dir / "example_application_edges.jsonl", required=False)
    existing_rule_cases = read_jsonl(args.layer_dir / "rule_cases.jsonl", required=False)
    rejected_archive = read_jsonl(args.layer_dir / "rejected_archive.jsonl", required=False)
    decisions = read_jsonl(args.decisions)

    final_core_nodes = [final_node(row, "core", "accepted_from_step6") for row in explicit_core_nodes]
    final_core_edges = [final_edge(row, "core", "accepted_from_step6") for row in explicit_core_edges]
    final_app_nodes = [final_node(row, "example_application", "accepted_from_step6") for row in existing_app_nodes]
    final_app_edges = [final_edge(row, "example_application", "accepted_from_step6") for row in existing_app_edges]
    final_rule_cases = [final_rule_case(row, "accepted_from_step6") for row in existing_rule_cases]

    archived = [
        archived_item(row, "rejected_before_step7", None, str(row.get("item_kind") or row.get("kind") or "unknown"))
        for row in rejected_archive
    ]
    deferred: list[dict[str, Any]] = []
    traces: list[dict[str, Any]] = []

    approved_decisions: list[dict[str, Any]] = []
    for decision in decisions:
        item = dict(decision)
        item["approval_label"] = args.approval_label
        approved_decisions.append(item)

    # Apply node decisions first so rewritten edges can resolve application-layer node ids.
    for decision in approved_decisions:
        if decision.get("item_kind") != "node":
            continue
        source = dict(decision.get("source_item") or {})
        recommendation = str(decision.get("recommendation") or "")
        target_layer = str(decision.get("target_layer") or "")

        if recommendation == "accept":
            if is_core_target_layer(target_layer):
                item = final_node(source, "core", "accepted_by_step7", decision)
                add_unique(final_core_nodes, item, node_identity)
            elif target_layer == "example_application":
                item = final_node(source, "example_application", "accepted_by_step7", decision)
                add_unique(final_app_nodes, item, node_identity)
            else:
                deferred.append(archived_item(source, "deferred_unknown_accept_target", decision, "node"))
                traces.append(trace_row(decision, "defer", note=f"unknown target_layer: {target_layer}"))
                continue
            traces.append(trace_row(decision, "accept", imported_item_id=node_identity(source)))
        elif recommendation == "rewrite":
            rewrite = decision.get("rewritten_item") or {}
            archived.append(
                archived_item(
                    source,
                    "rewritten_original_not_imported",
                    decision,
                    "node",
                    {"rewritten_item": rewrite},
                )
            )
            if rewrite.get("operation") == "merge_node":
                merged = merge_node_alias(final_core_nodes, str(rewrite.get("target_name") or ""), source, decision)
                note = "merged_into_existing_core_node" if merged else "merge_target_not_found_archive_only"
                traces.append(
                    trace_row(
                        decision,
                        "rewrite",
                        imported_item_id=str(rewrite.get("target_node_id") or rewrite.get("target_name") or ""),
                        archived_item_id=node_identity(source),
                        note=note,
                    )
                )
            else:
                traces.append(
                    trace_row(
                        decision,
                        "rewrite",
                        archived_item_id=node_identity(source),
                        note=str(decision.get("action_detail") or "rewritten_without_imported_node"),
                    )
                )
        elif recommendation == "reject":
            archived.append(archived_item(source, "rejected_by_step7", decision, "node"))
            traces.append(trace_row(decision, "reject", archived_item_id=node_identity(source)))
        else:
            deferred.append(archived_item(source, "deferred_after_step7", decision, "node"))
            traces.append(trace_row(decision, "defer", archived_item_id=node_identity(source)))

    nodes_by_name: dict[str, dict[str, Any]] = {}
    for node in [*final_core_nodes, *final_app_nodes]:
        name = str(node.get("name") or "")
        if name and name not in nodes_by_name:
            nodes_by_name[name] = node

    for decision in approved_decisions:
        if decision.get("item_kind") != "edge":
            continue
        source = dict(decision.get("source_item") or {})
        recommendation = str(decision.get("recommendation") or "")
        target_layer = str(decision.get("target_layer") or "")

        if recommendation == "accept":
            endpoints_ok, missing = edge_endpoints_exist(source, [*final_core_nodes, *final_app_nodes])
            if not endpoints_ok:
                deferred.append(
                    archived_item(
                        source,
                        "deferred_edge_endpoint_not_imported",
                        decision,
                        "edge",
                        {"missing_endpoints": missing},
                    )
                )
                traces.append(
                    trace_row(
                        decision,
                        "defer",
                        archived_item_id=edge_identity(source),
                        note="edge_endpoint_not_imported:" + ",".join(missing),
                    )
                )
                continue
            if is_core_target_layer(target_layer):
                item = final_edge(source, "core", "accepted_by_step7", decision)
                add_unique(final_core_edges, item, edge_identity)
            elif target_layer == "example_application":
                item = final_edge(source, "example_application", "accepted_by_step7", decision)
                add_unique(final_app_edges, item, edge_identity)
            else:
                deferred.append(archived_item(source, "deferred_unknown_accept_target", decision, "edge"))
                traces.append(trace_row(decision, "defer", note=f"unknown target_layer: {target_layer}"))
                continue
            traces.append(trace_row(decision, "accept", imported_item_id=edge_identity(source)))
        elif recommendation == "rewrite":
            rewrite = decision.get("rewritten_item") or {}
            if rewrite.get("operation") == "replace_edge":
                new_edge = enrich_rewritten_edge(rewrite, nodes_by_name)
                endpoints_ok, missing = edge_endpoints_exist(new_edge, [*final_core_nodes, *final_app_nodes])
                if not endpoints_ok:
                    deferred.append(
                        archived_item(
                            source,
                            "deferred_rewritten_edge_endpoint_not_imported",
                            decision,
                            "edge",
                            {"rewritten_item": new_edge, "missing_endpoints": missing},
                        )
                    )
                    traces.append(
                        trace_row(
                            decision,
                            "defer",
                            archived_item_id=edge_identity(source),
                            note="rewritten_edge_endpoint_not_imported:" + ",".join(missing),
                        )
                    )
                    continue
                item = final_edge(new_edge, str(new_edge.get("kg_layer") or "example_application"), "rewritten_by_step7", decision)
                added = add_unique(final_app_edges if item["kg_layer"] == "example_application" else final_core_edges, item, edge_identity)
                archived.append(
                    archived_item(
                        source,
                        "rewritten_original_not_imported",
                        decision,
                        "edge",
                        {"rewritten_item": item},
                    )
                )
                traces.append(
                    trace_row(
                        decision,
                        "rewrite",
                        imported_item_id=edge_identity(item),
                        archived_item_id=edge_identity(source),
                        note="rewritten_edge_imported" if added else "rewritten_edge_duplicate_skipped",
                    )
                )
            else:
                archived.append(archived_item(source, "rewrite_without_replacement_archived", decision, "edge"))
                traces.append(trace_row(decision, "rewrite", archived_item_id=edge_identity(source), note="missing replace_edge payload"))
        elif recommendation == "reject":
            archived.append(archived_item(source, "rejected_by_step7", decision, "edge"))
            traces.append(trace_row(decision, "reject", archived_item_id=edge_identity(source)))
        else:
            deferred.append(archived_item(source, "deferred_after_step7", decision, "edge"))
            traces.append(trace_row(decision, "defer", archived_item_id=edge_identity(source)))

    for decision in approved_decisions:
        if decision.get("item_kind") != "rule_case":
            continue
        source = dict(decision.get("source_item") or {})
        recommendation = str(decision.get("recommendation") or "")

        if recommendation == "accept":
            if not owner_exists(source, [*final_core_nodes, *final_app_nodes]):
                deferred.append(archived_item(source, "deferred_rule_case_owner_not_imported", decision, "rule_case"))
                traces.append(trace_row(decision, "defer", archived_item_id=rule_case_identity(source), note="owner_node_not_in_final_package"))
                continue
            item = final_rule_case(source, "accepted_by_step7", decision)
            added = add_unique(final_rule_cases, item, rule_case_identity)
            traces.append(
                trace_row(
                    decision,
                    "accept",
                    imported_item_id=rule_case_identity(item),
                    note="rule_case_imported" if added else "duplicate_rule_case_skipped",
                )
            )
        elif recommendation == "rewrite":
            rewrite = decision.get("rewritten_item") or {}
            archived.append(
                archived_item(
                    source,
                    "rewritten_original_not_imported",
                    decision,
                    "rule_case",
                    {"rewritten_item": rewrite},
                )
            )
            if rewrite.get("operation") == "replace_rule_case":
                new_case = dict(source)
                new_case.update({k: v for k, v in rewrite.items() if k != "operation"})
                if not new_case.get("rule_case_id"):
                    new_case["rule_case_id"] = rule_case_identity(new_case)
                if owner_exists(new_case, [*final_core_nodes, *final_app_nodes]):
                    item = final_rule_case(new_case, "rewritten_by_step7", decision)
                    added = add_unique(final_rule_cases, item, rule_case_identity)
                    traces.append(
                        trace_row(
                            decision,
                            "rewrite",
                            imported_item_id=rule_case_identity(item),
                            archived_item_id=rule_case_identity(source),
                            note="rewritten_rule_case_imported" if added else "rewritten_rule_case_duplicate_skipped",
                        )
                    )
                else:
                    deferred.append(archived_item(new_case, "deferred_rewritten_rule_case_owner_not_imported", decision, "rule_case"))
                    traces.append(
                        trace_row(
                            decision,
                            "defer",
                            archived_item_id=rule_case_identity(source),
                            note="rewritten_rule_case_owner_not_in_final_package",
                        )
                    )
            else:
                traces.append(
                    trace_row(
                        decision,
                        "rewrite",
                        archived_item_id=rule_case_identity(source),
                        note=str(decision.get("action_detail") or "rewritten_rule_case_without_replacement"),
                    )
                )
        elif recommendation == "reject":
            archived.append(archived_item(source, "rejected_by_step7", decision, "rule_case"))
            traces.append(trace_row(decision, "reject", archived_item_id=rule_case_identity(source)))
        else:
            deferred.append(archived_item(source, "deferred_after_step7", decision, "rule_case"))
            traces.append(trace_row(decision, "defer", archived_item_id=rule_case_identity(source)))

    section_groups, section_group_edges = build_section_groups([*final_core_nodes, *final_app_nodes])
    rule_groups, rule_group_edges = build_rule_groups(final_rule_cases)
    final_groups: list[dict[str, Any]] = []
    final_group_edges: list[dict[str, Any]] = []
    for group in [*section_groups, *rule_groups]:
        add_unique(final_groups, group, group_identity)
    for edge in [*section_group_edges, *rule_group_edges]:
        add_unique(final_group_edges, edge, group_member_identity)

    write_jsonl(out_dir / "final_core_nodes.jsonl", final_core_nodes)
    write_jsonl(out_dir / "final_core_edges.jsonl", final_core_edges)
    write_jsonl(out_dir / "final_application_nodes.jsonl", final_app_nodes)
    write_jsonl(out_dir / "final_application_edges.jsonl", final_app_edges)
    write_jsonl(out_dir / "final_rule_cases.jsonl", final_rule_cases)
    write_jsonl(out_dir / "final_knowledge_groups.jsonl", final_groups)
    write_jsonl(out_dir / "final_knowledge_group_edges.jsonl", final_group_edges)
    write_jsonl(out_dir / "final_archived_items.jsonl", archived)
    write_jsonl(out_dir / "final_rejected_items.jsonl", [row for row in archived if "reject" in str(row.get("archive_status") or "")])
    write_jsonl(out_dir / "final_review_pending.jsonl", deferred)
    write_jsonl(out_dir / "decision_trace.jsonl", traces)
    write_report(
        out_dir / "final_import_report.md",
        final_core_nodes,
        final_core_edges,
        final_app_nodes,
        final_app_edges,
        final_rule_cases,
        final_groups,
        final_group_edges,
        archived,
        deferred,
        traces,
    )

    print(f"[OK] final import package -> {out_dir}")
    print(f"[OK] core nodes/edges -> {len(final_core_nodes)}/{len(final_core_edges)}")
    print(f"[OK] application nodes/edges -> {len(final_app_nodes)}/{len(final_app_edges)}")
    print(f"[OK] rule cases -> {len(final_rule_cases)}")
    print(f"[OK] knowledge groups/edges -> {len(final_groups)}/{len(final_group_edges)}")
    print(f"[OK] archived/deferred -> {len(archived)}/{len(deferred)}")
    print(f"[OK] decision traces -> {len(traces)}")


if __name__ == "__main__":
    main()
